
import java.awt.CardLayout;
import javax.swing.JFrame;
import panelManager.DashboardPanel;
import panelManager.LogoutPanel;
import panelManager.ManageMenu;
import panelManager.ManageReservationPanel;
import panelManager.ManageRolesPanel;
import panelManager.SettingsPanel;
import panelManager.TrackSalesPanel;
import panels.SessionData;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class ManagerForm extends javax.swing.JFrame {

    private final SessionData sessionData = SessionData.getInstance(); // Singleton instance
    private CardLayout cardLayout;
    private final int managerId;
    private String managerName;

    /**
     * Creates new form ManagerForm
     */
    public ManagerForm() {
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setTitle("Manager Dashboard");
        setSize(1000, 700);
        setLocationRelativeTo(null);

        this.managerId = sessionData.getUserId();
        this.managerName = sessionData.getUserName();

        initComponents();
        initializePanels();

        if (managerName != null && !managerName.isEmpty()) {
            label5.setText("Welcome, " + managerName);
        } else {
            label5.setText("Welcome, Guest");
        }
    }
    private void initializePanels() {
        cardLayout = new CardLayout();
        contentPanel.setLayout(cardLayout);

        // Adding panels for different functionalities
        contentPanel.add(new DashboardPanel(), "Dashboard"); // Updated to use ManagerDashboardPanel
        contentPanel.add(new ManageMenu(), "Manage Menu");
        contentPanel.add(new ManageReservationPanel(), "Manage Reservation");
        contentPanel.add(new ManageRolesPanel(), "Manage Role");
        contentPanel.add(new TrackSalesPanel(), "Track Sales");
        contentPanel.add(new SettingsPanel(), "Settings");
        contentPanel.add(new LogoutPanel(), "Logout");
    }

    public void switchToPanel(String panelName) {
        cardLayout.show(contentPanel, panelName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel4 = new javax.swing.JPanel();
        label5 = new javax.swing.JLabel();
        button29 = new java.awt.Button();
        button30 = new java.awt.Button();
        button31 = new java.awt.Button();
        button32 = new java.awt.Button();
        button33 = new java.awt.Button();
        button34 = new java.awt.Button();
        button35 = new java.awt.Button();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(699, 769));

        sidePanel4.setBackground(new java.awt.Color(153, 0, 153));
        sidePanel4.setPreferredSize(new java.awt.Dimension(323, 354));

        label5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("jLabel1");

        button29.setBackground(new java.awt.Color(204, 0, 204));
        button29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button29.setForeground(new java.awt.Color(255, 255, 255));
        button29.setLabel("Dashboard");
        button29.setName("button1"); // NOI18N
        button29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button30.setBackground(new java.awt.Color(204, 0, 204));
        button30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button30.setForeground(new java.awt.Color(255, 255, 255));
        button30.setLabel("Track Sales");
        button30.setName("button1"); // NOI18N
        button30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button31.setBackground(new java.awt.Color(204, 0, 204));
        button31.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button31.setForeground(new java.awt.Color(255, 255, 255));
        button31.setLabel("Settings");
        button31.setName("button1"); // NOI18N
        button31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button32.setBackground(new java.awt.Color(204, 0, 204));
        button32.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button32.setForeground(new java.awt.Color(255, 255, 255));
        button32.setLabel("Manage Reservations");
        button32.setName("button1"); // NOI18N
        button32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button33.setBackground(new java.awt.Color(204, 0, 204));
        button33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button33.setForeground(new java.awt.Color(255, 255, 255));
        button33.setLabel("Manage Menu");
        button33.setName("button1"); // NOI18N
        button33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button34.setBackground(new java.awt.Color(204, 0, 204));
        button34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button34.setForeground(new java.awt.Color(255, 255, 255));
        button34.setLabel("Manage Roles");
        button34.setName("button1"); // NOI18N
        button34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        button35.setBackground(new java.awt.Color(204, 0, 204));
        button35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button35.setForeground(new java.awt.Color(255, 255, 255));
        button35.setLabel("Logout");
        button35.setName("button1"); // NOI18N
        button35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanel4Layout = new javax.swing.GroupLayout(sidePanel4);
        sidePanel4.setLayout(sidePanel4Layout);
        sidePanel4Layout.setHorizontalGroup(
            sidePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addComponent(button29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(button34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(button30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(button32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(button33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(button31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(button35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidePanel4Layout.setVerticalGroup(
            sidePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(button29, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(button34, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(button30, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(button32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(button33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 312, Short.MAX_VALUE)
                .addComponent(button31, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(button35, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "Logout");
    }//GEN-LAST:event_button7ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "Manage Role");
    }//GEN-LAST:event_button6ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "Manage Menu");
    }//GEN-LAST:event_button5ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "Manage Reservation");
    }//GEN-LAST:event_button4ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "Settings");
    }//GEN-LAST:event_button3ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "Track Sales");
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "Dashboard");
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button29;
    private java.awt.Button button30;
    private java.awt.Button button31;
    private java.awt.Button button32;
    private java.awt.Button button33;
    private java.awt.Button button34;
    private java.awt.Button button35;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel label5;
    private javax.swing.JPanel sidePanel4;
    // End of variables declaration//GEN-END:variables
}
